// <auto-generated />
using System;
using IncomeTaxCalculator.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IncomeTaxCalculator.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.18");

            modelBuilder.Entity("IncomeTaxCalculator.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossAnnualSalary")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "John",
                            GrossAnnualSalary = 40000m,
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Jane",
                            GrossAnnualSalary = 50000m,
                            LastName = "Doe"
                        });
                });

            modelBuilder.Entity("IncomeTaxCalculator.API.Models.TaxBand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LowerLimit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UpperLimit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaxBands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LowerLimit = 0m,
                            Name = "Tax Band A",
                            TaxRate = 0m,
                            UpperLimit = 5000m
                        },
                        new
                        {
                            Id = 2,
                            LowerLimit = 5000m,
                            Name = "Tax Band B",
                            TaxRate = 20m,
                            UpperLimit = 20000m
                        },
                        new
                        {
                            Id = 3,
                            LowerLimit = 20000m,
                            Name = "Tax Band C",
                            TaxRate = 40m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
